apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesample
  name: kubesample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesample
  template:
    metadata:
      labels:
        app: kubesample
    spec:
      containers:
      - image: saravak/kubesample
        name: kubesample
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: '0.5'
            memory: 100Mi
        command:
          - "node"
          - "$(OPTIONS)"
          - "index.js"
        env: 
          - name: appport
            valueFrom:
              configMapKeyRef:
                name: kubesample
                key: port
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: kubesample
                key: environment
          - name: OPTIONS
            valueFrom:
              configMapKeyRef:
                name: kubesample
                key: node_options
        volumeMounts:
          - mountPath: /app/dev/status.html
            name: staticfile
            subPath: status.html
      volumes:
        - name: staticfile
          configMap: 
            name: kubesample
              
